---
title: "Base Salary by Pay Base"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: cosmo
---


```{r}
library(tidyverse)
library(janitor)
library(viridis)
library(plotly)
library(ggplot2)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

```{r}
payroll_data = 
    read_csv("data/payroll_data.csv")
```

```{r}
number_job_titles_plot =
  payroll_data %>%
  group_by(county_name, job_title) %>%
  summarise(count = n()) %>%
  ungroup() %>% 
  group_by(county_name) %>%
  summarise(count = n()) %>%
        ggplot(aes(x = reorder(county_name, count), y = count, fill = county_name)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_y_continuous(
      labels = scales::comma,
    limits = c(0, 1500),
    breaks = seq(0, 1500, by = 250)) +
  labs(
    x = "County Names",
    y = "Number of Job Titles",
    title = "The Number of Job Titles Held By Municipal Employees of New York State By County",
    fill = "New York State County Names"
  ) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

number_job_titles_plot
```


```{r}
Ls_bar = payroll_data %>%
  group_by(leave_status) %>%
  summarise(
    count = n())

ggplot(Ls_bar, aes(x = leave_status, y = count, fill = leave_status)) + geom_bar(position = "dodge", stat = "identity") + labs(title = "The Number of Employees by Municipality Separated  by Leave Status", x = "Leave Status", y = "Number of Employees") + scale_y_continuous(labels = scales::comma)
```

```{r}
Total_ls = table(pull(payroll_data,leave_status))

Total_ls


labels = c("Active", "Ceased", "On Leave")

piepercent = round(100 * Total_ls / sum(Total_ls), 1)

par(xpd = TRUE) 
pie(Total_ls, labels = paste(labels, sep = " ", piepercent, "%"),
    main = "Percentages of Municipal Employees by Leave Status", col = viridis(length(Total_ls)))
legend("topright", c("Active", "Ceased", "On Leave"),cex = 0.9, fill = viridis(length(Total_ls)))
```

# Total Number of Job Titles by New York State Counties Plot

```{r}
number_job_titles_plot =
  payroll_data %>%
  group_by(county_name, job_title) %>%
  summarise(count = n()) %>%
  ungroup() %>% 
  group_by(county_name) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = reorder(county_name, count), y = count, fill = county_name)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_y_continuous(
      labels = scales::comma,
    limits = c(0, 1500),
    breaks = seq(0, 1500, by = 250)) +
  labs(
    x = "County Names",
    y = "Number of Job Titles",
    title = "The Number of Job Titles Held By Municipal Employees of New York State By County",
    fill = "New York State County Names"
  ) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

number_job_titles_plot
```

# Plot for Top 10 Job Titles Throughout the New York State Counties

```{r}
job_frequency =
payroll_data %>%
    group_by(county_name, job_title) %>%
    summarise(job_frequency = n()) %>%
    arrange(desc(job_frequency)) %>%
    ungroup()

job_frequency_data = 
    job_frequency %>%
    top_n(job_frequency, n = 10) %>%
    mutate(
     job_title = recode(job_title, "TEACHER- PER SESSION" = "TEACHER PER SESSION"),
     job_title = recode(job_title, "ANNUAL ED PARA" = "EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "TEACHER SPECIAL EDUCATION" = "SPECIAL EDUCATION TEACHER"),
     job_title = recode(job_title, "TEACHER-GENERAL ED" = "GENERAL EDUCATION TEACHER"),
     job_title = recode(job_title, "SUBSTITUTE ED PARA" = "SUBSTITUTE EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "F/T SCHOOL AIDE" = "SCHOOL AIDE"))
    
job_frequency_plot =
    job_frequency_data %>%
    ggplot(aes(x = reorder(job_title, job_frequency), y = job_frequency, fill = county_name)) +
  geom_bar(position = "dodge", stat = "identity") + 
    scale_y_continuous(
      labels = scales::comma,
    limits = c(0, 120000),
    breaks = seq(0, 120000, by = 10000)) +
  labs(
    x = "Top 10 Job Titles",
    y = "Frequency of Job Titles",
    title = "The Top 10 Job Titles Held By Municipal Employees Throughout the Counties in New York State",
    fill = "New York State County Names"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

job_frequency_plot
```

# The Top Five Job Titles Held by Municipal Employees in Six New York State Counties Plot

```{r}
top5_freq = 
  payroll_data %>%
   filter(county_name %in% c("NEW YORK", "KINGS", "BRONX", "QUEENS", "RICHMOND","ALBANY")) %>%
   group_by(county_name, job_title) %>%
   summarise(number_of_people = n()) %>%
   arrange(desc(number_of_people)) %>%
   slice(1:5)

top5_freq_n = 
  top5_freq %>%
   mutate(
     job_title = as.factor(job_title),
     job_title = recode(job_title, "TEACHER- PER SESSION" = "TEACHER PER SESSION"),
     job_title = recode(job_title, "ANNUAL ED PARA" = "EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "TEACHER SPECIAL EDUCATION" = "SPECIAL EDUCATION TEACHER"),
     job_title = recode(job_title, "ASST DIR OF INTERGVNMENTAL RELTNS FOR THE ALBANY OFFICE" = "ASSISTANT DIRECTOR OF INTERNATIONAL RELATIONS"),
     job_title = recode(job_title, "EMERGENCY MEDICAL SPECIALIST-EMT" = "EMT"))
 
top_plot = 
  ggplot(top5_freq_n, aes(x = reorder(job_title, number_of_people), y = number_of_people)) + geom_point(aes(color = county_name), alpha = 0.5) + 
scale_y_continuous(
  labels = scales::comma,
  limits = c(0,120000),
  breaks = seq(0, 120000, by = 15000)) + 
labs(title = "The Top Five Job Titles Held by Municipal Employees in Six New York State Counties",x = "Job Title", y = "Number of Municipal Employees")  + 
  guides(color = guide_legend(title = "New York State County Names")) +
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

top_plot
```

# Plot for Top 10 Job Titles Throughout the New York County

```{r}
job_frequency_newyork =
payroll_data %>%
    filter(county_name == "NEW YORK") |> 
    group_by(county_name, job_title) %>%
    summarise(job_frequency = n()) %>%
    arrange(desc(job_frequency)) %>%
    ungroup()

job_frequency_newyork_data = 
    job_frequency_newyork %>%
    top_n(job_frequency, n = 10) %>%
    mutate(
     job_title = recode(job_title, "TEACHER- PER SESSION" = "TEACHER PER SESSION"),
     job_title = recode(job_title, "ANNUAL ED PARA" = "EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "TEACHER SPECIAL EDUCATION" = "SPECIAL EDUCATION TEACHER"),
     job_title = recode(job_title, "TEACHER-GENERAL ED" = "GENERAL EDUCATION TEACHER"),
     job_title = recode(job_title, "SUBSTITUTE ED PARA" = "SUBSTITUTE EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "F/T SCHOOL AIDE" = "SCHOOL AIDE"))
    
job_frequency_newyork_plot =
    job_frequency_newyork_data %>%
    ggplot(aes(x = reorder(job_title, job_frequency), y = job_frequency, fill = county_name)) +
  geom_bar(position = "dodge", stat = "identity") + 
    scale_y_continuous(
      labels = scales::comma,
    limits = c(0, 120000),
    breaks = seq(0, 120000, by = 10000)) +
  labs(
    x = "Top 10 Job Titles",
    y = "Frequency of Job Titles",
    title = "The Top 10 Job Titles Held By Municipal Employees in New York County",
    fill = "New York State County Names"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

job_frequency_newyork_plot
```

# Plot for Top 10 Job Titles Throughout Albany County

```{r}
job_frequency_albany =
payroll_data %>%
    filter(county_name == "ALBANY") |> 
    group_by(county_name, job_title) %>%
    summarise(job_frequency = n()) %>%
    arrange(desc(job_frequency)) %>%
    ungroup()

job_frequency_albany_data = 
    job_frequency_albany %>%
    top_n(job_frequency, n = 10) %>%
    mutate(
     job_title = recode(job_title, "TEACHER- PER SESSION" = "TEACHER PER SESSION"),
     job_title = recode(job_title, "ANNUAL ED PARA" = "EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "TEACHER SPECIAL EDUCATION" = "SPECIAL EDUCATION TEACHER"),
     job_title = recode(job_title, "TEACHER-GENERAL ED" = "GENERAL EDUCATION TEACHER"),
     job_title = recode(job_title, "SUBSTITUTE ED PARA" = "SUBSTITUTE EDUCATION PARAPROFESSIONAL"),
     job_title = recode(job_title, "F/T SCHOOL AIDE" = "SCHOOL AIDE"))
    
job_frequency_albany_plot =
    job_frequency_albany_data %>%
    ggplot(aes(x = reorder(job_title, job_frequency), y = job_frequency, fill = county_name)) +
  geom_bar(position = "dodge", stat = "identity") + 
    scale_y_continuous(
      labels = scales::comma,
    limits = c(0, 5),
    breaks = seq(0, 5, by = 1)) +
  labs(
    x = "Top 10 Job Titles",
    y = "Frequency of Job Titles",
    title = "The Top 10 Job Titles Held By Municipal Employeesin Albany County",
    fill = "New York State County Names"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 

job_frequency_albany_plot
```
