---
title: "Statistical Tests"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: cosmo
---


```{r}
library(tidyverse)
library(janitor)
library(viridis)
library(plotly)
library(ggplot2)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

```{r}
payroll_data = 
    read_csv("data/payroll_data.csv")
```


# ANOVA Analysis

Null Hypothesis(Ho) = The mean base salary is constant for all counties

Alternative Hypothesis(H1) = The mean base salary is different for all municipalities

```{r}
ms_model = 
  payroll_data %>%
  mutate(county_name = as.factor(county_name)) %>%
  group_by(county_name) %>%
  summarise(ms_mean = base_salary)

res = lm(ms_mean ~ factor(county_name), data = ms_model)

anova_analysis = 
    anova(res) %>% 
    broom::tidy() %>% 
    knitr::kable(caption = "One Way Anova Test for Mean Salary by County")

anova_analysis
```

# Tukey test for Mean Salary by County

```{r}
res1 = aov(ms_mean ~ factor(county_name), data = ms_model)

tukey_ms = TukeyHSD(res1)

tukey_ms

tukey_table = 
    tukey_ms %>% 
    broom::tidy() %>%
    knitr::kable(caption = "Tukey Test for Mean Salary by County")

tukey_table
```
